### ISSUE TITLE
Img2Img

### ISSUE THREAD

**Issue by Omarsmsm** [cubiq/Block_Patcher_ComfyUI#5]
I was wondering if as a feature you could add start at step end at step so we could try img2img with this?

I know this is super alpha but i think could be useful

**Comment by Omarsmsm** [comment]
I got GPT 01 to write this and it seems to work.

https://gist.github.com/Omarsmsm/107a27fb760ecb8160667eecb5f0c8b6

**Comment by cubiq** [comment]
yeah I will add this, it's pretty easy to do

**Comment by cubiq** [comment]
should work now
